--- #YAML:1.0
name:                Net-DNSBL-MultiDaemon
version:             0.37
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::SafeDO:                  0.12
    Net::DNS::Codes:               0.09
    Net::DNS::ToolKit:             0.47
    Net::NBsocket:                 0.23
    NetAddr::IP:                   4.067
    Test::More:                    0
    Unix::Syslog:                  0.97
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
