# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DNSBL-MultiDaemon
version:      0.22
version_from: MultiDaemon.pm
installdirs:  site
requires:
    Geo::IP::PurePerl:             1.1
    Net::DNS::Codes:               0.08
    Net::DNS::ToolKit:             0.24
    NetAddr::IP::Lite:             0.02
    Unix::Syslog:                  0.97

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
